name: django-notes 


on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: self-hosted


    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Sync latest code on self-hosted runner
        run: |
          echo "Pulling the latest code..."
          cd //home/ubuntu/actions-runner/django-notes-app
          git pull origin main


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'






      
      - name: Build Docker image
        run: docker build --no-cache -t django-notes-image .


      - name: Check if the container is running, then stop and remove it
        run: |
          if docker ps -q --filter "name=django-notes-container"; then
            echo "Stopping and removing container django-notes-container.."
            docker stop django-notes-container || true
            docker rm django-notes-container || true
          else
            echo "Container django-notes-container is not running. Skipping stop and remove."
          fi


      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name django-notes-container django-notes-image
