name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Debug step to confirm the presence of pom.xml
      - name: Check directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files:"
          ls -alh

      # Debug: Check Java version
      - name: Verify Java Version
        run: java -version

      # Debug: Check Maven version
      - name: Verify Maven Version
        run: mvn -v

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build with Maven
      - name: Build with Maven (Verbose)
        run: mvn -X clean install -f pom.xml  # This will enable full debug logging

      # SonarQube scan
      - name: SonarQube Scan
        run: |
          docker run --rm --network container:sonarqube_container_name \
            -e SONAR_HOST_URL="http://sonarqube:9000" \
            -e SONAR_TOKEN=$SONAR_TOKEN \
            -v $(pwd):/usr/src \
            sonarsource/sonar-scanner-cli
